package compilations.WordServicePackage;


/**
* compilations/WordServicePackage/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordService.idl
* Saturday, May 24, 2025 4:10:34 PM PST
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor


  public GameNotFoundException (String $reason)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFoundException
