package compilations;


/**
* compilations/_LoginServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public class _LoginServiceStub extends org.omg.CORBA.portable.ObjectImpl implements LoginService
{

  public LoginResult loginPlayer (String username, String password) throws InvalidCredentialsException, UserAlreadyLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("loginPlayer", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                LoginResult $result = LoginResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:compilations/InvalidCredentialsException:1.0"))
                    throw InvalidCredentialsExceptionHelper.read ($in);
                else if (_id.equals ("IDL:compilations/UserAlreadyLoggedInException:1.0"))
                    throw UserAlreadyLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return loginPlayer (username, password        );
            } finally {
                _releaseReply ($in);
            }
  } // loginPlayer

  public LoginResult loginAdmin (String username, String password) throws InvalidCredentialsException, UserAlreadyLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("loginAdmin", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                LoginResult $result = LoginResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:compilations/InvalidCredentialsException:1.0"))
                    throw InvalidCredentialsExceptionHelper.read ($in);
                else if (_id.equals ("IDL:compilations/UserAlreadyLoggedInException:1.0"))
                    throw UserAlreadyLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return loginAdmin (username, password        );
            } finally {
                _releaseReply ($in);
            }
  } // loginAdmin

  public LoginResult forceLoginPlayer (String username, String password, String table) throws InvalidCredentialsException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("forceLoginPlayer", true);
                $out.write_string (username);
                $out.write_string (password);
                $out.write_string (table);
                $in = _invoke ($out);
                LoginResult $result = LoginResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:compilations/InvalidCredentialsException:1.0"))
                    throw InvalidCredentialsExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return forceLoginPlayer (username, password, table        );
            } finally {
                _releaseReply ($in);
            }
  } // forceLoginPlayer

  public void logoutPlayer (String sessionId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logoutPlayer", true);
                $out.write_string (sessionId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                logoutPlayer (sessionId        );
            } finally {
                _releaseReply ($in);
            }
  } // logoutPlayer

  public boolean isSessionActive (String sessionId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("isSessionActive", true);
                $out.write_string (sessionId);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return isSessionActive (sessionId        );
            } finally {
                _releaseReply ($in);
            }
  } // isSessionActive

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:compilations/LoginService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "compilations._LoginServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LoginServiceStub
