package compilations;

/**
* compilations/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminServiceHelper.type ();
  }

}
