package compilations;


/**
* compilations/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public interface AdminServiceOperations 
{
  void createPlayerAccount (String username, String password) throws PlayerAlreadyExistsException;
  void removePlayerAccount (String username) throws PlayerNotFoundException;
  void updatePlayerCredentials (String currentUsername, String newUsername, String newPassword) throws PlayerNotFoundException, PlayerAlreadyExistsException;
  PlayerAccount[] searchPlayerAccounts (String keyword);
  void updateGameWaitTime (short seconds);
  void updateRoundDuration (short seconds);
  short getJoinTimeout ();
  short getRoundDuration ();
  GameSessionObject[] getGameHistory ();
} // interface AdminServiceOperations
