package compilations;

/**
* compilations/GameSessionObjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class GameSessionObjectHolder implements org.omg.CORBA.portable.Streamable
{
  public GameSessionObject value = null;

  public GameSessionObjectHolder ()
  {
  }

  public GameSessionObjectHolder (GameSessionObject initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameSessionObjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameSessionObjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameSessionObjectHelper.type ();
  }

}
