package compilations;

/**
* compilations/GameNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

public final class GameNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameNotFoundException value = null;

  public GameNotFoundExceptionHolder ()
  {
  }

  public GameNotFoundExceptionHolder (GameNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameNotFoundExceptionHelper.type ();
  }

}
