package compilations;

/**
* compilations/GameManagerServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/


//new
public final class GameManagerServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameManagerService value = null;

  public GameManagerServiceHolder ()
  {
  }

  public GameManagerServiceHolder (GameManagerService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameManagerServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameManagerServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameManagerServiceHelper.type ();
  }

}
