package compilations;


/**
* compilations/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public interface GameServiceOperations 
{
  void requestToJoinGame (String username) throws NoOpponentFoundException;
  WordMaskInfo getCurrentWordMask (String username) throws GameNotFoundException;
  void submitLetterGuess (String username, char letter) throws InvalidGuessException, GameNotFoundException;
  short getRemainingGuesses (String username) throws GameNotFoundException;
  String getGameProgressStatus (String username) throws GameNotFoundException;
  void setPlayerDone (String username, short round, boolean guessedCorrectly) throws GameNotFoundException;
  short getCurrentPlayerCount ();
  String[] getAllPlayers () throws GameNotFoundException;
  boolean areAllPlayersDone (String username, short round) throws GameNotFoundException;
  boolean advanceToNextRoundIfReady (String username, short round) throws GameNotFoundException;
  PlayerScore[] getAllPlayerScores ();
  short getCurrentRound (String gameId) throws GameNotFoundException;
  boolean isGameOver ();
  String getWinner ();
  String getScoreSummary ();

  //NEW UPDATE NG IDL NATIN -jas
  void createGameSession ();
  void createGameDetails () throws GameNotFoundException;
  void createRound (String gameId) throws GameNotFoundException;
  void updateGame (String status) throws GameNotFoundException;
  void updateRound (String status) throws GameNotFoundException;
  String readRoundWord () throws GameNotFoundException;
  void deleteGameSession () throws GameNotFoundException;
  String getRoundId (String gameId) throws GameNotFoundException;
} // interface GameServiceOperations
