package compilations;


/**
* compilations/GameSessionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

abstract public class GameSessionHelper
{
  private static String  _id = "IDL:compilations/GameSession:1.0";

  public static void insert (org.omg.CORBA.Any a, GameSession that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameSession extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "gameId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "timeCreated",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "word",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "playerUsernames",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "status",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "players",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (GameSessionHelper.id (), "GameSession", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameSession read (org.omg.CORBA.portable.InputStream istream)
  {
    GameSession value = new GameSession ();
    value.gameId = istream.read_string ();
    value.timeCreated = istream.read_string ();
    value.word = istream.read_string ();
    int _len0 = istream.read_long ();
    value.playerUsernames = new String[_len0];
    for (int _o1 = 0;_o1 < value.playerUsernames.length; ++_o1)
      value.playerUsernames[_o1] = istream.read_string ();
    value.status = istream.read_string ();
    int _len1 = istream.read_long ();
    value.players = new String[_len1];
    for (int _o2 = 0;_o2 < value.players.length; ++_o2)
      value.players[_o2] = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameSession value)
  {
    ostream.write_string (value.gameId);
    ostream.write_string (value.timeCreated);
    ostream.write_string (value.word);
    ostream.write_long (value.playerUsernames.length);
    for (int _i0 = 0;_i0 < value.playerUsernames.length; ++_i0)
      ostream.write_string (value.playerUsernames[_i0]);
    ostream.write_string (value.status);
    ostream.write_long (value.players.length);
    for (int _i1 = 0;_i1 < value.players.length; ++_i1)
      ostream.write_string (value.players[_i1]);
  }

}
