package compilations;


/**
* compilations/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor

  public GameNotFoundException (String _message)
  {
    super(GameNotFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public GameNotFoundException (String $reason, String _message)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class GameNotFoundException
