package compilations;


/**
* compilations/GameSessionSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

public final class GameSessionSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public GameSession value[] = null;

  public GameSessionSeqHolder ()
  {
  }

  public GameSessionSeqHolder (GameSession[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameSessionSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameSessionSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameSessionSeqHelper.type ();
  }

}
