package compilations;


/**
* compilations/GameManagerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/


//new
public interface GameManagerServiceOperations 
{
  String joinOrCreateGameSession (String username);
  GameSession[] listActiveGameSessions ();

  //NEW UPDATE NG IDL NATIN -jas
  GameStatus[] getGameStatus () throws GameNotFoundException;
} // interface GameManagerServiceOperations
