package compilations;


/**
* compilations/GameSessionSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

abstract public class GameSessionSeqHelper
{
  private static String  _id = "IDL:compilations/GameSessionSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, GameSession[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameSession[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = GameSessionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (GameSessionSeqHelper.id (), "GameSessionSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameSession[] read (org.omg.CORBA.portable.InputStream istream)
  {
    GameSession value[] = null;
    int _len0 = istream.read_long ();
    value = new GameSession[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = GameSessionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameSession[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      GameSessionHelper.write (ostream, value[_i0]);
  }

}
