package compilations;


/**
* compilations/GamePlayerScoreSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public final class GamePlayerScoreSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerScore value[] = null;

  public GamePlayerScoreSequenceHolder ()
  {
  }

  public GamePlayerScoreSequenceHolder (PlayerScore[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GamePlayerScoreSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GamePlayerScoreSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GamePlayerScoreSequenceHelper.type ();
  }

}
