package compilations;


/**
* compilations/GameConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class GameConfiguration implements org.omg.CORBA.portable.IDLEntity
{
  public short waitTime = (short)0;
  public short roundDuration = (short)0;

  public GameConfiguration ()
  {
  } // ctor

  public GameConfiguration (short _waitTime, short _roundDuration)
  {
    waitTime = _waitTime;
    roundDuration = _roundDuration;
  } // ctor

} // class GameConfiguration
