package compilations;

/**
* compilations/GameStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

public final class GameStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public GameStatus value = null;

  public GameStatusHolder ()
  {
  }

  public GameStatusHolder (GameStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameStatusHelper.type ();
  }

}
