package compilations;


/**
* compilations/GameStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

public final class GameStatus implements org.omg.CORBA.portable.IDLEntity
{

  //new
  public String gameId = null;
  public String status = null;

  public GameStatus ()
  {
  } // ctor

  public GameStatus (String _gameId, String _status)
  {
    gameId = _gameId;
    status = _status;
  } // ctor

} // class GameStatus
