package compilations;

/**
* compilations/GameConfigurationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class GameConfigurationHolder implements org.omg.CORBA.portable.Streamable
{
  public GameConfiguration value = null;

  public GameConfigurationHolder ()
  {
  }

  public GameConfigurationHolder (GameConfiguration initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameConfigurationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameConfigurationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameConfigurationHelper.type ();
  }

}
