package compilations;


/**
* compilations/GameSession.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/

public final class GameSession implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public String timeCreated = null;
  public String word = null;
  public String playerUsernames[] = null;
  public String status = null;
  public String players[] = null;

  public GameSession ()
  {
  } // ctor

  public GameSession (String _gameId, String _timeCreated, String _word, String[] _playerUsernames, String _status, String[] _players)
  {
    gameId = _gameId;
    timeCreated = _timeCreated;
    word = _word;
    playerUsernames = _playerUsernames;
    status = _status;
    players = _players;
  } // ctor

} // class GameSession
