package compilations;


/**
* compilations/GameSessionObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class GameSessionObject implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public String timeCreated = null;
  public String status = null;

  public GameSessionObject ()
  {
  } // ctor

  public GameSessionObject (String _gameId, String _timeCreated, String _status)
  {
    gameId = _gameId;
    timeCreated = _timeCreated;
    status = _status;
  } // ctor

} // class GameSessionObject
