package compilations;


/**
* compilations/GameManagerServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/


//new
public abstract class GameManagerServicePOA extends org.omg.PortableServer.Servant
 implements GameManagerServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("joinOrCreateGameSession", new Integer (0));
    _methods.put ("listActiveGameSessions", new Integer (1));
    _methods.put ("getGameStatus", new Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // compilations/GameManagerService/joinOrCreateGameSession
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.joinOrCreateGameSession (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // compilations/GameManagerService/listActiveGameSessions
       {
         GameSession $result[] = null;
         $result = this.listActiveGameSessions ();
         out = $rh.createReply();
         GameSessionSeqHelper.write (out, $result);
         break;
       }


  //NEW UPDATE NG IDL NATIN -jas
       case 2:  // compilations/GameManagerService/getGameStatus
       {
         try {
           GameStatus $result[] = null;
           $result = this.getGameStatus ();
           out = $rh.createReply();
           GameStatusMapHelper.write (out, $result);
         } catch (GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           GameNotFoundExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:compilations/GameManagerService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameManagerService _this() 
  {
    return GameManagerServiceHelper.narrow(
    super._this_object());
  }

  public GameManagerService _this(org.omg.CORBA.ORB orb) 
  {
    return GameManagerServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameManagerServicePOA
