package compilations;


/**
* compilations/GameManagerServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameManagerService.idl
* Saturday, May 24, 2025 4:21:35 PM PST
*/


//new
abstract public class GameManagerServiceHelper
{
  private static String  _id = "IDL:compilations/GameManagerService:1.0";

  public static void insert (org.omg.CORBA.Any a, GameManagerService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameManagerService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameManagerServiceHelper.id (), "GameManagerService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameManagerService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameManagerServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameManagerService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameManagerService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameManagerService)
      return (GameManagerService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameManagerServiceStub stub = new _GameManagerServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameManagerService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameManagerService)
      return (GameManagerService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GameManagerServiceStub stub = new _GameManagerServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
