package compilations;


/**
* compilations/InvalidGuessException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public final class InvalidGuessException extends org.omg.CORBA.UserException
{

  public InvalidGuessException ()
  {
    super(InvalidGuessExceptionHelper.id());
  } // ctor


  public InvalidGuessException (String $reason)
  {
    super(InvalidGuessExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidGuessException
