package compilations;

/**
* compilations/InvalidCredentialsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public final class InvalidCredentialsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidCredentialsException value = null;

  public InvalidCredentialsExceptionHolder ()
  {
  }

  public InvalidCredentialsExceptionHolder (InvalidCredentialsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidCredentialsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidCredentialsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidCredentialsExceptionHelper.type ();
  }

}
