package compilations;

/**
* compilations/InvalidGuessExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public final class InvalidGuessExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidGuessException value = null;

  public InvalidGuessExceptionHolder ()
  {
  }

  public InvalidGuessExceptionHolder (InvalidGuessException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidGuessExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidGuessExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidGuessExceptionHelper.type ();
  }

}
