package compilations;


/**
* compilations/InvalidCredentialsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public final class InvalidCredentialsException extends org.omg.CORBA.UserException
{

  public InvalidCredentialsException ()
  {
    super(InvalidCredentialsExceptionHelper.id());
  } // ctor


  public InvalidCredentialsException (String $reason)
  {
    super(InvalidCredentialsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidCredentialsException
