package compilations;


/**
* compilations/LeaderboardServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

public abstract class LeaderboardServicePOA extends org.omg.PortableServer.Servant
 implements LeaderboardServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getTopPlayers", new Integer (0));
    _methods.put ("recordPlayerWin", new Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // compilations/LeaderboardService/getTopPlayers
       {
         PlayerScore $result[] = null;
         $result = this.getTopPlayers ();
         out = $rh.createReply();
         PlayerScoreSeqHelper.write (out, $result);
         break;
       }

       case 1:  // compilations/LeaderboardService/recordPlayerWin
       {
         String username = in.read_string ();
         this.recordPlayerWin (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:compilations/LeaderboardService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LeaderboardService _this() 
  {
    return LeaderboardServiceHelper.narrow(
    super._this_object());
  }

  public LeaderboardService _this(org.omg.CORBA.ORB orb) 
  {
    return LeaderboardServiceHelper.narrow(
    super._this_object(orb));
  }


} // class LeaderboardServicePOA
