package compilations;


/**
* compilations/LeaderboardServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

abstract public class LeaderboardServiceHelper
{
  private static String  _id = "IDL:compilations/LeaderboardService:1.0";

  public static void insert (org.omg.CORBA.Any a, LeaderboardService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LeaderboardService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LeaderboardServiceHelper.id (), "LeaderboardService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LeaderboardService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LeaderboardServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LeaderboardService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LeaderboardService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LeaderboardService)
      return (LeaderboardService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LeaderboardServiceStub stub = new _LeaderboardServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LeaderboardService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LeaderboardService)
      return (LeaderboardService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LeaderboardServiceStub stub = new _LeaderboardServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
