package compilations;


/**
* compilations/LeaderboardServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

public interface LeaderboardServiceOperations 
{
  PlayerScore[] getTopPlayers ();
  void recordPlayerWin (String username);
} // interface LeaderboardServiceOperations
