package compilations;

/**
* compilations/LeaderboardServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

public final class LeaderboardServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public LeaderboardService value = null;

  public LeaderboardServiceHolder ()
  {
  }

  public LeaderboardServiceHolder (LeaderboardService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LeaderboardServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LeaderboardServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LeaderboardServiceHelper.type ();
  }

}
