package compilations;

/**
* compilations/LoginResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public final class LoginResultHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginResult value = null;

  public LoginResultHolder ()
  {
  }

  public LoginResultHolder (LoginResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginResultHelper.type ();
  }

}
