package compilations;


/**
* compilations/LoginServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public interface LoginServiceOperations 
{
  LoginResult loginPlayer (String username, String password) throws InvalidCredentialsException, UserAlreadyLoggedInException;
  LoginResult loginAdmin (String username, String password) throws InvalidCredentialsException, UserAlreadyLoggedInException;
  LoginResult forceLoginPlayer (String username, String password, String table) throws InvalidCredentialsException;
  void logoutPlayer (String sessionId);
  boolean isSessionActive (String sessionId);
} // interface LoginServiceOperations
