package compilations;

/**
* compilations/LoginServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public final class LoginServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginService value = null;

  public LoginServiceHolder ()
  {
  }

  public LoginServiceHolder (LoginService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginServiceHelper.type ();
  }

}
