package compilations;


/**
* compilations/LoginServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

abstract public class LoginServiceHelper
{
  private static String  _id = "IDL:compilations/LoginService:1.0";

  public static void insert (org.omg.CORBA.Any a, LoginService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LoginService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LoginServiceHelper.id (), "LoginService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LoginService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LoginServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LoginService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LoginService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LoginService)
      return (LoginService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LoginServiceStub stub = new _LoginServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LoginService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LoginService)
      return (LoginService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LoginServiceStub stub = new _LoginServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
