package compilations;


/**
* compilations/NoOpponentFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public final class NoOpponentFoundException extends org.omg.CORBA.UserException
{

  public NoOpponentFoundException ()
  {
    super(NoOpponentFoundExceptionHelper.id());
  } // ctor


  public NoOpponentFoundException (String $reason)
  {
    super(NoOpponentFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoOpponentFoundException
