package compilations;

/**
* compilations/NoOpponentFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public final class NoOpponentFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public NoOpponentFoundException value = null;

  public NoOpponentFoundExceptionHolder ()
  {
  }

  public NoOpponentFoundExceptionHolder (NoOpponentFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NoOpponentFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NoOpponentFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NoOpponentFoundExceptionHelper.type ();
  }

}
