package compilations;


/**
* compilations/PlayerScoreSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

public final class PlayerScoreSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerScore value[] = null;

  public PlayerScoreSeqHolder ()
  {
  }

  public PlayerScoreSeqHolder (PlayerScore[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerScoreSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerScoreSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerScoreSeqHelper.type ();
  }

}
