package compilations;

/**
* compilations/PlayerAccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerAccountHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerAccount value = null;

  public PlayerAccountHolder ()
  {
  }

  public PlayerAccountHolder (PlayerAccount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerAccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerAccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerAccountHelper.type ();
  }

}
