package compilations;


/**
* compilations/PlayerScoreHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

abstract public class PlayerScoreHelper
{
  private static String  _id = "IDL:compilations/PlayerScore:1.0";

  public static void insert (org.omg.CORBA.Any a, PlayerScore that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PlayerScore extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "username",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "gamesWon",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PlayerScoreHelper.id (), "PlayerScore", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PlayerScore read (org.omg.CORBA.portable.InputStream istream)
  {
    PlayerScore value = new PlayerScore ();
    value.username = istream.read_string ();
    value.gamesWon = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PlayerScore value)
  {
    ostream.write_string (value.username);
    ostream.write_short (value.gamesWon);
  }

}
