package compilations;

/**
* compilations/PlayerNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerNotFoundException value = null;

  public PlayerNotFoundExceptionHolder ()
  {
  }

  public PlayerNotFoundExceptionHolder (PlayerNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerNotFoundExceptionHelper.type ();
  }

}
