package compilations;

/**
* compilations/PlayerAlreadyExistsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerAlreadyExistsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerAlreadyExistsException value = null;

  public PlayerAlreadyExistsExceptionHolder ()
  {
  }

  public PlayerAlreadyExistsExceptionHolder (PlayerAlreadyExistsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerAlreadyExistsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerAlreadyExistsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerAlreadyExistsExceptionHelper.type ();
  }

}
