package compilations;


/**
* compilations/PlayerAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerAlreadyExistsException extends org.omg.CORBA.UserException
{

  public PlayerAlreadyExistsException ()
  {
    super(PlayerAlreadyExistsExceptionHelper.id());
  } // ctor


  public PlayerAlreadyExistsException (String $reason)
  {
    super(PlayerAlreadyExistsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerAlreadyExistsException
