package compilations;


/**
* compilations/PlayerScore.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

public final class PlayerScore implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public short gamesWon = (short)0;

  public PlayerScore ()
  {
  } // ctor

  public PlayerScore (String _username, short _gamesWon)
  {
    username = _username;
    gamesWon = _gamesWon;
  } // ctor

} // class PlayerScore
