package compilations;


/**
* compilations/PlayerAccountSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerAccountSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerAccount value[] = null;

  public PlayerAccountSeqHolder ()
  {
  }

  public PlayerAccountSeqHolder (PlayerAccount[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerAccountSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerAccountSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerAccountSeqHelper.type ();
  }

}
