package compilations;


/**
* compilations/PlayerNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerNotFoundException extends org.omg.CORBA.UserException
{

  public PlayerNotFoundException ()
  {
    super(PlayerNotFoundExceptionHelper.id());
  } // ctor


  public PlayerNotFoundException (String $reason)
  {
    super(PlayerNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerNotFoundException
