package compilations;

/**
* compilations/PlayerScoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LeaderboardService.idl
* Saturday, May 24, 2025 4:10:12 PM PST
*/

public final class PlayerScoreHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerScore value = null;

  public PlayerScoreHolder ()
  {
  }

  public PlayerScoreHolder (PlayerScore initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerScoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerScoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerScoreHelper.type ();
  }

}
