package compilations;


/**
* compilations/PlayerAccount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, May 24, 2025 4:21:25 PM PST
*/

public final class PlayerAccount implements org.omg.CORBA.portable.IDLEntity
{
  public int playerId = (int)0;
  public String username = null;
  public String password = null;
  public short gamesWon = (short)0;
  public boolean loggedIn = false;

  public PlayerAccount ()
  {
  } // ctor

  public PlayerAccount (int _playerId, String _username, String _password, short _gamesWon, boolean _loggedIn)
  {
    playerId = _playerId;
    username = _username;
    password = _password;
    gamesWon = _gamesWon;
    loggedIn = _loggedIn;
  } // ctor

} // class PlayerAccount
