package compilations;

/**
* compilations/UserAlreadyLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public final class UserAlreadyLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public UserAlreadyLoggedInException value = null;

  public UserAlreadyLoggedInExceptionHolder ()
  {
  }

  public UserAlreadyLoggedInExceptionHolder (UserAlreadyLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UserAlreadyLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UserAlreadyLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UserAlreadyLoggedInExceptionHelper.type ();
  }

}
