package compilations;


/**
* compilations/UserAlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Saturday, May 24, 2025 4:10:23 PM PST
*/

public final class UserAlreadyLoggedInException extends org.omg.CORBA.UserException
{

  public UserAlreadyLoggedInException ()
  {
    super(UserAlreadyLoggedInExceptionHelper.id());
  } // ctor


  public UserAlreadyLoggedInException (String $reason)
  {
    super(UserAlreadyLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class UserAlreadyLoggedInException
