package compilations;

/**
* compilations/WordServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordService.idl
* Saturday, May 24, 2025 4:10:34 PM PST
*/

public final class WordServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public WordService value = null;

  public WordServiceHolder ()
  {
  }

  public WordServiceHolder (WordService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordServiceHelper.type ();
  }

}
