package compilations;


import compilations.WordServicePackage.GameNotFoundException;

/**
* compilations/WordServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordService.idl
* Saturday, May 24, 2025 4:10:34 PM PST
*/

public interface WordServiceOperations 
{
  String getNewWord (String gameId);
  void markWordAsUsed (String word, String gameId);
  String getCurrentWord (String gameId);
  void clearCurrentWord (String gameId);

  //NEW METHOD BELOW-JAS
  String getRoundWord (String gameid, String roundid) throws GameNotFoundException;
} // interface WordServiceOperations
