package compilations;


/**
* compilations/WordMaskInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, May 24, 2025 4:10:05 PM PST
*/

public final class WordMaskInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String maskedWord = null;
  public String actualWord = null;
  public short remainingGuesses = (short)0;
  public String gameId = null;

  public WordMaskInfo ()
  {
  } // ctor

  public WordMaskInfo (String _maskedWord, String _actualWord, short _remainingGuesses, String _gameId)
  {
    maskedWord = _maskedWord;
    actualWord = _actualWord;
    remainingGuesses = _remainingGuesses;
    gameId = _gameId;
  } // ctor

} // class WordMaskInfo
