package compilations;


/**
* compilations/WordService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordService.idl
* Saturday, May 24, 2025 4:10:34 PM PST
*/

public interface WordService extends WordServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordService
