# DO NOT EDIT THIS FILE!
#
# Python module compilations generated by omniidl

import omniORB
omniORB.updateModule("compilations")

# ** 1. Stub files contributing to this module
from Client_Python.compilations import GameManagerService_idl

# ** 2. Sub-modules

# ** 3. End
